apiVersion: demo.anthos.com/v1
kind: CompositeCluster 
metadata:
  name: gke-cluster
spec:
  compositionRef:
    # Possible values cluster-gcp-gke, cluster-aws-eks, cluster-azure-aks
    name: cluster-aws-eks
  parameters:
    location: "us-central-1c"
    nodeSize: medium  # Possible values small, medium, large
    k8sVersion: "1.25"
    fleetProject: "111111111"
    minNodeCount: 2
    adminUsers:
    - bkauf@google.com  
     #Azure Specific 
    resourceGroup: abc
  writeConnectionSecretToRef:
    namespace: default
    name: b-team
