#Example Composition to creaet an Azure AKS cluster
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: cluster-azure-aks
  labels:
    crossplane.io/xrd: compositeclusters.demo.anthos.com
    provider: azure
    cluster: aks
spec:
  compositeTypeRef:
    apiVersion: demo.anthos.com/v1
    kind:  CompositeCluster
  patchSets:
  - name: metadata
    patches:
    - fromFieldPath: metadata.labels
  resources:
  - name: akscluster
    base:
      apiVersion: containerservice.azure.gke.cloud.google.com/v1beta1
      kind: KubernetesCluster
      metadata:
        labels:
          role: controlplane
       # name: akscluster
      spec:
        providerConfigRef: 
          name: default-azure
        forProvider:
          defaultNodePool:
            - name: default
              nodeCount: 1
              vmSize: Standard_D2_v2
          dnsPrefix: akscluster
          identity:
            - type: SystemAssigned
          location: East Us
          resourceGroupName: xyz
          kubernetesVersion: "1.25"
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.clusterName
      toFieldPath: metadata.annotations[crossplane.io/external-name]
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.k8sVersion
      toFieldPath: spec.forProvider.kubernetesVersion
    - fromFieldPath: spec.parameters.location
      toFieldPath: spec.forProvider.location
    - fromFieldPath: spec.parameters.resourceGroup
      toFieldPath: spec.forProvider.resourceGroupName
    - fromFieldPath: spec.parameters.minNodeCount
      toFieldPath: spec.forProvider.defaultNodePool[0].nodeCount
    - fromFieldPath: spec.parameters.nodeSize
      toFieldPath: spec.forProvider.defaultNodePool[0].vmSize
      transforms:
        - type: map
          map:
            small: Standard_D2_v2
            medium: Standard_B4ms
            large: Standard_D8s_v3
    - type: ToCompositeFieldPath
      fromFieldPath: metadata.annotations[crossplane.io/external-name]
      toFieldPath: status.clusterName
    - type: ToCompositeFieldPath
      fromFieldPath: spec.forProvider.location
      toFieldPath: status.region
