#example GKE on GCP node pool creation
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: gcp-gke-nodepool
  labels:
    crossplane.io/xrd: compositenodepools.demo.anthos.com
    provider: gcp
    cluster: gke
spec:
  compositeTypeRef:
    apiVersion: demo.anthos.com/v1
    kind:  CompositeNodepool
  patchSets:
  - name: metadata
    patches:
    - fromFieldPath: metadata.labels
  resources:
  - name: nodepool
    base:
      apiVersion: container.gcp.gke.cloud.google.com/v1beta1
      kind: NodePool
      metadata:
        annotations:
      spec:
        providerConfigRef: 
          name: default-gcp
        forProvider:
          cluster: test-cluster
          #version: 1.25
          nodeConfig:
            - machineType: e2-medium
              oauthScopes:
                - https://www.googleapis.com/auth/cloud-platform
              serviceAccount: 261832825633-compute@developer.gserviceaccount.com
    patches:
    - fromFieldPath: spec.parameters.clusterName
      toFieldPath: spec.forProvider.cluster
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.location
      toFieldPath: spec.forProvider.location
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.minNodeCount
      toFieldPath: spec.forProvider.nodeCount
    - fromFieldPath: spec.parameters.nodeSize
      toFieldPath: spec.forProvider.nodeConfig[0].machineType
      transforms:
        - type: map
          map:
            small: e2-small
            medium: e2-medium
            large: e2-standard-2
