apiVersion: demo.anthos.com/v1
kind: Cluster
metadata:
  name: gke-cluster
  labels:
    cluster-owner: abc
spec:
  compositionRef:
      # Possible values cluster-gcp-gke, cluster-aws-eks, cluster-azure-aks
    name: cluster-gcp-gke
  parameters:
    location: "us-east4"
    clusterName: "gke-cluster"
    nodeSize: medium  # Possible values small, medium, large
    k8sVersion: "1.24"
    fleetProject: "111111" #GCP project ID
    minNodeCount: 2
    adminUsers:
    - example@google.com
    #Azure Specific 
    resourceGroup: abc
