apiVersion: demo.anthos.com/v1
kind: Cluster
metadata:
  name: gke-cluster
  labels:
    cluster-owner: abc
spec:
  compositionRef:
      # Possible values cluster-gcp-gke, cluster-aws-eks, cluster-azure-aks
    name: cluster-gcp-gke
  parameters:
    # Possible values small, medium, large
    nodeSize: small
    k8sVersion: "1.24"
    fleetProject: "111111"
    minNodeCount: 2
    adminUsers:
    - example@google.com
    #Azure Specific 
    resourceGroup: abc
