apiVersion: demo.anthos.com/v1
kind: NodePool
metadata:
  name: test-nodepool
spec:
  compositionRef:
    # Possible values gcp-node-pool
    name: gcp-gke-nodepool
  parameters:
    clusterName: "cluster-1"
    location: "us-central1-c"	
    # Possible values small, medium, large
    nodeSize: medium
    minNodeCount: 1
