#Example of importing a GKE  node pool into a composition 
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: import-gcp-gke-nodepool
  labels:
    crossplane.io/xrd: compositenodepools.demo.anthos.com
    provider: gcp
    cluster: gke
spec:
  compositeTypeRef:
    apiVersion: demo.anthos.com/v1
    kind:  CompositeNodepool
  patchSets:
  - name: metadata
    patches:
    - fromFieldPath: metadata.labels
  resources:
  - name: nodepool
    base:
      apiVersion: container.gcp.gke.cloud.google.com/v1beta1
      kind: NodePool
      metadata:
        annotations:
          crossplane.io/external-name: pool-2
      spec:
        providerConfigRef: 
          name: default-gcp
        forProvider:
          cluster: test-cluster
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.managementPolicy
      toFieldPath: spec.managementPolicy
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.nodePoolName
      toFieldPath: metadata.annotations[crossplane.io/external-name]
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.clusterName
      toFieldPath: spec.forProvider.cluster
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.location
      toFieldPath: spec.forProvider.nodeLocations[0]
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.location
      toFieldPath: spec.forProvider.location
